name: Psalm Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  static-analysis:
    name: Static Analysis with Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # Change to your project's PHP version
          extensions: mbstring, xml, pdo, sqlite
          coverage: none

      # - name: Install Composer dependencies
      #   run: composer install --no-progress --no-suggest --prefer-dist

      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
          security_analysis: true
          report_file: results.sarif
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
